/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'david' at '16-11-27 上午12:52' with Gradle 3.0
 *
 * @author david, @date 16-11-27 上午12:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
